// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obmifjpnwzniogqteobi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ibWlmanBud3puaW9ncXRlb2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjAxNjcsImV4cCI6MjA2NTQ5NjE2N30.GOGZf7QIsc-OVG-cDj1cNcvV314crlupay-HYXqLc_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);